// Golden vectors were generated by running the real Python implementation
// (tagger/tagger_app/core/metadata.py:759 calculate_similarity) on 2026-10-04.
const {
  calculateSimilarity,
  cleanForSimilarity,
  sequenceMatcherRatio
} = require('../../src/shared/similarity');

describe('shared/similarity (port of tagger calculate_similarity)', () => {
  describe('cleanForSimilarity', () => {
    it('lowercases, strips .cbz, bracketed groups, volume and issue markers', () => {
      expect(cleanForSimilarity('Batman   #001 (2016) (Digital) (Zone-Empire).cbz')).toBe('batman');
      expect(cleanForSimilarity('Saga Vol 1')).toBe('saga');
      expect(cleanForSimilarity('DIE!')).toBe('die');
      expect(cleanForSimilarity('The Amazing Spider-Man')).toBe('the amazing spider man');
    });

    it('does not strip non-cbz extensions (matches the Python source)', () => {
      expect(cleanForSimilarity('Batman.cbr')).toBe('batman cbr');
    });
  });

  describe('sequenceMatcherRatio (difflib Ratcliff-Obershelp)', () => {
    it('computes 2M/T', () => {
      expect(sequenceMatcherRatio('abc', 'abc')).toBe(1);
      expect(sequenceMatcherRatio('abc', 'xyz')).toBe(0);
      expect(sequenceMatcherRatio('batman', 'batmen')).toBeCloseTo(5 / 6, 10);
    });
  });

  describe('calculateSimilarity golden vectors', () => {
    const vectors = [
      ['Watchmen (2019)', 'Watchmen', 1.0],
      ['Batman   #001 (2016) (Digital) (Zone-Empire).cbz', 'Batman', 1.0],
      ['Asterix and the Secret Weapon', 'Asterix and the Secret Weapon (1991)', 1.0],
      ['One Piece v105', 'One Piece', 1.0],
      ['Saga', 'Saga Vol 1', 1.0],
      ['DIE', 'DIE!', 1.0],
      ['The Amazing Spider-Man', 'Amazing Spider-Man', 0.9],
      ['X-Men Vol. 2 #003', 'X Men 2 3', 0.7142857142857143],
      ['Assorted Crisis Events v01 (2025) (Digital) (DR & Quinch-Empire).cbz', 'Crisis', 0.42857142857142855],
      ['Batman', 'Batmen', 0.8333333333333334],
      ['', 'Batman', 0.0],
      ['Batman', 'Batman', 1.0]
    ];

    for (const [a, b, expected] of vectors) {
      it(`calculateSimilarity(${JSON.stringify(a)}, ${JSON.stringify(b)}) === ${expected}`, () => {
        expect(calculateSimilarity(a, b)).toBeCloseTo(expected, 10);
      });
    }

    it('returns 0.90 for a >=85% substring match, before difflib', () => {
      // 'southern bastard' is a 94% substring of 'southern bastards' -> the rule returns 0.90
      // even though difflib alone would score ~0.97.
      expect(calculateSimilarity('Southern Bastards', 'Southern Bastard')).toBe(0.9);
    });

    it('returns 0 for empty/whitespace input', () => {
      expect(calculateSimilarity('', '')).toBe(0);
      expect(calculateSimilarity(null, 'Batman')).toBe(0);
      expect(calculateSimilarity('   ', 'Batman')).toBe(0);
    });
  });
});
